### PR TITLE
Montage as an instance

### LINKED ISSUE #7: ABORT_OP doesn't undo epoch registration of payloads
For operations adding new payloads in the nonblocking structure, `BEGIN_OP` takes payloads and register corresponding epoch number in the payloads. However, such registration should be undo, i.e., epoch number in the payloads should be reset to `NULL_EPOCH`, when `ABORT_OP` occurs. 
`ABORT_OP` means CAS fail and we should release the epoch we occupied.

### PR DESCRIPTION
**Pull request by roghnin**
Refactor the code to have all Montage-related stuff in an instance. Three steps:

1. Put all initialization and finalization into rideables;
2. Instantiate montage
3. Use object-oriented APIs in rideables.

### CODE REVIEW

**Comment by roghnin** [comment]
Some modifications are made to DCSS-related code in the last two commits. Please take a look when you have time. Thanks @qtcwt

File: src/Rideable.hpp [hunk 1]
```diff
@@ -10,9 +10,11 @@
 
 
 class GlobalTestConfig;
+class LocalTestConfig;
 
 class Rideable{
 public:
+	virtual void init_thread(GlobalTestConfig* gtc, LocalTestConfig* ltc){};
```
Comment (qtcwt) [inline src/Rideable.hpp:17]: Are we assuming that all apps using Montage have to inherit their data structures from `Rideable`?

File: src/persist/common_macros.hpp [hunk 2]
```diff
@@ -0,0 +1,18 @@
+#ifndef COMMON_MACROS_HPP
+#define COMMON_MACROS_HPP
+
+namespace pds{
+#define INIT_EPOCH 3
+#define NULL_EPOCH 0
```
Comment (qtcwt) [inline src/persist/common_macros.hpp:6]: FWIW, macros usually don't act as we think in namespace, as far as I know. We may want to use `const int` if we want to restrict its scope by namespace. Same suggestion to the macro functions below---perhaps make them inline?

File: src/persist/PersistStructs.cpp [hunk 3]
```diff
@@ -0,0 +1,22 @@
+#include "PersistStructs.hpp"
+#include "EpochSys.hpp"
+
+namespace pds{
+
+void sc_desc_t::try_complete(EpochSys* esys, uint64_t addr){
+    nbptr_t _d = nbptr.load();
+    int ret = 0;
```
Comment (qtcwt) [inline src/persist/PersistStructs.cpp]: Whoops, `ret` is for debugging.

File: src/tests/ChurnTest.hpp [hunk 4]
```diff
@@ -109,11 +108,11 @@ void ChurnTest::init(GlobalTestConfig* gtc){
 	assert(sigaction(SIGUSR1, &sa, NULL) == 0);
 #endif
 
-	// init Persistent allocator
-	Persistent::init();
+	// // init Persistent allocator
+	// Persistent::init();
```
Comment (qtcwt) [inline src/tests/ChurnTest.hpp]: Could you tell me where these "routines" are called now? How are essential data structures initialized after refactoring?

**Comment by qtcwt** [comment]
> Some modifications are made to DCSS-related code in the last two commits. Please take a look when you have time. Thanks @qtcwt

I've added some comments to what I didn't fully understand/we could optimize, relevant or irrelevant to DCSS.  The rest looks pretty good to me. Thanks!

File: src/Rideable.hpp (hunk 1 above)
Comment (roghnin) [reply src/Rideable.hpp:17]: No we we're not, but we assume all apps using Montage have to inherit from `Recoverable`.
It's not done yet -- all apps will need to call something like `montage->init_thread()`, and `Rideable::init_thread()` is just a wrapper for that.

File: src/tests/ChurnTest.hpp (hunk 4 above)
Comment (roghnin) [reply src/tests/ChurnTest.hpp]: It's in the constructor of `Recoverable` right now.

File: src/persist/PersistStructs.cpp (hunk 3 above)
Comment (roghnin) [reply src/persist/PersistStructs.cpp]: Do you want me to get rid of it? Or you can commit on this branch.

File: src/persist/common_macros.hpp (hunk 2 above)
Comment (roghnin) [reply src/persist/common_macros.hpp:6]: This is a good point; thanks.
Macros like PNEW may not be easily replaced with inline functions -- C++'s variadic arguments has different semantics from macro `__VA_ARGS__`. Moreover, I think field-generating logic can only be done by preprocessor without compiler support.
I'm thinking of getting rid of namespace `pds`, adding common prefix to macros and put functions into classes. You'll see how this goes.

File: src/persist/PersistStructs.cpp (hunk 3 above)
Comment (qtcwt) [reply src/persist/PersistStructs.cpp]: You can just delete them in your next commit. Thanks!

**Comment by roghnin** [comment]
@qtcwt This PR is ready for review.

1. There are two sets of API's in `src/persist/api` directory. I'm hoping to always use the object-oriented api and abandon the other, but I'm not sure how it's integrated into threadcached. Can you take a look?
2. DCSS-related API's have been slightly modified again, and the code are scattered across three files: `src/persist/PersistStructs.hpp`, `src/persist/api/Recoverable.hpp` and `src/persist/api/Recoverable.cpp`. All montage-based NB data structures have been updated to use the new APIs.
3. "API" section in `src/persist/EpochSys.hpp` seems redundant to stuff in `src/persist/api/Recoverable.hpp` -- I'm planning to merge everything into the latter, together with `epochs` and `pending_allocs`, since they logically belong to a data structure rather than an `EpochSys` instance.

Thanks.

**Comment by qtcwt** [comment]
> 1. There are two sets of API's in `src/persist/api` directory. I'm hoping to always use the object-oriented api and abandon the other, but I'm not sure how it's integrated into threadcached. Can you take a look?

I would slightly prefer to keep both sets of APIs because some programs, such as Memcached, are not object-oriented, and may find it inconvenient to use OO API.
If we really want to keep only one, we could create a dummy global `Recoverable` object in Memcached and call functions of this object. See what you think.

> 2. DCSS-related API's have been slightly modified again, and the code are scattered across three files: `src/persist/PersistStructs.hpp`, `src/persist/api/Recoverable.hpp` and `src/persist/api/Recoverable.cpp`. All montage-based NB data structures have been updated to use the new APIs.

Thanks. I'll replace `nbptr` with `lin_var`, a better name for this class, I think.
One question: why do we need an extra file of `PersistStructs.hpp`? Could stuffs in it be merged to `Recoverable.hpp`?

> 3. "API" section in `src/persist/EpochSys.hpp` seems redundant to stuff in `src/persist/api/Recoverable.hpp` -- I'm planning to merge everything into the latter, together with `epochs` and `pending_allocs`, since they logically belong to a data structure rather than an `EpochSys` instance.

By giving this another thought, I agree with you: moving them to `Recoverable` results in better programmability.

I'm going to review all changed files and leave in-line comments.

File: src/persist/EpochSys.cpp [hunk 5]
```diff
@@ -1,20 +1,10 @@
...
-    EpochSys* esys = nullptr;
-    padded<uint64_t>* epochs = nullptr;
-    SysMode sys_mode = ONLINE;
-    // std::atomic<size_t> abort_cnt(0);
-    // std::atomic<size_t> total_cnt(0);
-
-    UIDGenerator PBlk::uid_generator;
-    
-    padded<sc_desc_t>* local_descs = nullptr;
+    thread_local int EpochSys::tid = -1;
```
Comment (qtcwt) [inline src/persist/EpochSys.cpp:7]: What's this `tid` for? I thought each instance of `EpochSys` already has `tid` included?

File: src/persist/EpochSys.hpp [hunk 6]
```diff
@@ -13,281 +13,35 @@
...
-    };
-
-    friend class EpochSysVerifyTest;
-    
 private:
     // persistent fields:
     Epoch* epoch_container = nullptr;
     std::atomic<uint64_t>* global_epoch = nullptr;
 
+    // semi-persistent fields:
```
Comment (qtcwt) [inline src/persist/EpochSys.hpp:127]: What does it mean by "semi-persistent fields"? (And perhaps it is singular rather than plural?) Do we need to persist the UID generator? If so how do we reserve its state durably now...

File: src/persist/api/Recoverable.cpp [hunk 7]
```diff
@@ -0,0 +1,46 @@
+#include "Recoverable.hpp"
+
+Recoverable::Recoverable(GlobalTestConfig* gtc){
+    // init Persistent allocator
+    // TODO: put this into EpochSys.
```
Comment (qtcwt) [inline src/persist/api/Recoverable.cpp:5]: Perhaps this TODO is outdated?

File: src/persist/api/Recoverable.cpp [hunk 8]
```diff
@@ -0,0 +1,46 @@
...
+
+void Recoverable::init_thread(int tid){
+    _esys->init_thread(tid);
+}
+
+namespace pds{
+
+    void sc_desc_t::try_complete(Recoverable* ds, uint64_t addr){
+        lin_var _d = var.load();
+        // int ret = 0;
```
Comment (qtcwt) [inline src/persist/api/Recoverable.cpp:37]: Thanks :)

File: src/persist/pnew.hpp [hunk 9]
```diff
@@ -0,0 +1,14 @@
+// NOTE: don't include this file elsewhere!
+// this is supposed to be a part of Recoverable.hpp
+
+// TODO: replace `new` operator of T with
+// per-heap allocation and placement new.
+template <typename T, typename... Types> 
+T* pnew(Types... args) 
+{ 
+    T* ret = new T(args...);
```
Comment (qtcwt) [inline src/persist/pnew.hpp]: I optimized a little here in commit [204c67](https://github.com/urcs-sync/Montage/pull/3/commits/204c67fccfe7b0628c477d4b8b48d22ebb4d524c). Hope I got your idea correctly.

File: src/tests/MapTest.hpp [hunk 10]
```diff
@@ -241,8 +235,7 @@ class MapTest : public Test{
         Savitar_core_finalize();
         pthread_mutex_destroy(&snapshot_lock);
 #endif
-        pds::finalize();
-        Persistent::finalize();
+        delete m;
```
Comment (qtcwt) [inline src/tests/MapTest.hpp:238]: Are we moving all destructions to the end of the tests?

File: src/tests/KVTest.hpp [hunk 11]
```diff
@@ -39,14 +39,9 @@ class KVTest : public Test{
         }
     }
     void parInit(GlobalTestConfig* gtc, LocalTestConfig* ltc){
-        pds::init_thread(ltc->tid);
+        m->init_thread(gtc, ltc);
```
Comment (qtcwt) [inline src/tests/KVTest.hpp:42]: delete m in cleanup?

File: src/tests/HeapChurnTest.hpp [hunk 12]
```diff
@@ -29,15 +28,10 @@ class HeapChurnTest : public Test{
     inline V fromInt(uint64_t v);
 
     void parInit(GlobalTestConfig* gtc, LocalTestConfig* ltc){
-        pds::init_thread(ltc->tid);
+        q->init_thread(gtc, ltc);
```
Comment (qtcwt) [inline src/tests/HeapChurnTest.hpp:31]: delete q in cleanup?

File: src/tests/SetChurnTest.hpp [hunk 13]
```diff
@@ -28,7 +28,6 @@ class SetChurnTest : public ChurnTest{
 		}
 	}
 	void doPrefill(GlobalTestConfig* gtc){
-		pds::init_thread(0);
 		// prefill deterministically:
```
Comment (qtcwt) [inline src/tests/SetChurnTest.hpp:31]: delete s in cleanup?

File: src/tests/ToyTest.hpp [hunk 14]
```diff
@@ -27,7 +26,7 @@ class ToyTest : public Test{
 
 	// called by all threads in parallel
 	void parInit(GlobalTestConfig* gtc, LocalTestConfig* ltc){
-        // pds::init_thread(ltc->tid);
+        t->init_thread(gtc, ltc);
```
Comment (qtcwt) [inline src/tests/ToyTest.hpp:29]: kinda trivial: delete t in cleanup?

File: src/persist/PersistStructs.hpp [hunk 15]
```diff
@@ -0,0 +1,279 @@
+#ifndef PERSIST_STRUCTS_HPP
```
Comment (qtcwt) [inline src/persist/PersistStructs.hpp]: Why do we need this extra file? Could they be merged into `Recoverable.hpp`?

File: src/rideables/MontageMSQueue.hpp [hunk 16]
```diff
@@ -29,20 +28,23 @@ class MontageMSQueue : public RQueue<T>{
 
 private:
     struct Node{
-        atomic_nbptr_t<Node*> next;
+        MontageMSQueue* ds;
```
Comment (qtcwt) [inline src/rideables/MontageMSQueue.hpp]: (Applicable to all data structures) I suggest to make this a reference (e.g., MontageMSQueue&), to make code more cpp-ish (using less pointers).

Comment (qtcwt) [reply src/rideables/MontageMSQueue.hpp]: That said, storing pointer/reference to a parent instance in all nodes is still awkward. I don't have a better idea for now though..

File: src/persist/EpochSys.hpp [hunk 17]
```diff
@@ -296,15 +50,31 @@ class EpochSys{
...
 
-    EpochSys(GlobalTestConfig* _gtc) : gtc(_gtc) {
+    // system mode that toggles on/off PDELETE for recovery purpose.
+    SysMode sys_mode = ONLINE;
+
+    /* public members for API */ // TODO: put these into Recoverable
+    // current epoch of each thread.
+    padded<uint64_t>* epochs = nullptr;
+    // containers for pending allocations
+    padded<std::unordered_set<PBlk*>>* pending_allocs = nullptr;
```
Comment (qtcwt) [inline src/persist/EpochSys.hpp]: Wentao's TODO: sanity check of `pending_allocs`

**Review by qtcwt — COMMENTED** [review]
Most of them are great to me. Thanks! Below are some questions and suggestions. 
I'm going to do a sanity check of `pending_allocs` related stuffs. Then I'll implement the multi-instance support of Ralloc.

File: src/persist/EpochSys.cpp (hunk 5 above)
Comment (roghnin) [reply src/persist/EpochSys.cpp:7]: It's a compromise -- I don't think it's possible to have `thread_local` members of an object -- it's not self-contained. Any better ideas?

Comment (qtcwt) [reply src/persist/EpochSys.cpp:7]: Oh is this global `tid` for the set of the global API?

Comment (roghnin) [reply src/persist/EpochSys.cpp:7]: No they're using the same one. I should perhaps have a different set of tid's for OO API.

File: src/persist/PersistStructs.hpp (hunk 15 above)
Comment (roghnin) [reply src/persist/PersistStructs.hpp]: We need this to be included by `EpochSys.hpp`. `Recoverable.hpp` is at the end of the dependency chain.

File: src/persist/api/Recoverable.cpp (hunk 7 above)
Comment (roghnin) [reply src/persist/api/Recoverable.cpp:5]: No. I'll do this in a different PR. In short, multiple `Recoverable` can share one `EpochSys` instance.

File: src/persist/pnew.hpp (hunk 9 above)
Comment (roghnin) [reply src/persist/pnew.hpp]: Oh I don't know we can do that... Thanks a lot! I think I can put this back to `Recoverable.hpp` and delete this file.

File: src/rideables/MontageMSQueue.hpp (hunk 16 above)
Comment (roghnin) [reply src/rideables/MontageMSQueue.hpp]: The issue here is to let destructor know which data structure is responsible for the reclamation of payload(s). We kind of have to do this as destructors don't take arguments.

File: src/tests/HeapChurnTest.hpp (hunk 12 above)
Comment (roghnin) [reply src/tests/HeapChurnTest.hpp:31]: Yes. Nice catch.

File: src/tests/MapTest.hpp (hunk 10 above)
Comment (roghnin) [reply src/tests/MapTest.hpp:238]: Yes. We didn't do that but we should. We need destruction of `Recoverable` to finish up `EpochSys` instances.

**Review by roghnin — COMMENTED** [review]
Thanks! I'll address all comments in the next several commits.

File: src/persist/EpochSys.cpp (hunk 5 above)
Comment (roghnin) [reply src/persist/EpochSys.cpp:7]: It turns out harder to do that I thought, or fundamentally impossible to do efficiently. Other per-thread structures need such an ID to index into, and nothing is as efficient as a `thread_local` ID. I can perhaps have a mapping from `std::this_thread::get_id` to everything else, but I'm afraid that's gonna be a significant overhead.

File: src/persist/EpochSys.hpp (hunk 6 above)
Comment (roghnin) [reply src/persist/EpochSys.hpp:127]: This is an interesting problem. UID generator needs to be persisted _somehow_ (we don't want it to generate existing IDs after recovery), but it doesn't worth to be persisted _precisely_, since persisting on every UID generation eats up the performance advantage of buffered durability.
The idea here is we persist a "boundary" every 2^x IDs, for all IDs smaller than that boundary. After a crash-recovery, we continue from that boundary.

**Review by roghnin — COMMENTED** [review]
I think `lin_var` is a nice name. Thanks!

**Comment by roghnin** [comment]
> I would slightly prefer to keep both sets of APIs because some programs, such as Memcached, are not object-oriented, and may find it inconvenient to use OO API.
> If we really want to keep only one, we could create a dummy global `Recoverable` object in Memcached and call functions of this object. See what you think.

I'll leave them as they are then. Currently the global API has one global `EpochSys` object in the background, as shown in the cpp file.

> One question: why do we need an extra file of `PersistStructs.hpp`? Could stuffs in it be merged to `Recoverable.hpp`?

I wasn't able to resolve the include dependencies at first, but I think I can do something similar right now.

File: src/persist/EpochSys.cpp (hunk 5 above)
Comment (qtcwt) [reply src/persist/EpochSys.cpp:7]: Ohhhhh sorry I misunderstood something here. This line is for initializing the static thread local tid in EpochSys. I thought it was another global thread local tid. Sorry. I'm marking this conversation resolved.

File: src/persist/api/Recoverable.cpp (hunk 7 above)
Comment (qtcwt) [reply src/persist/api/Recoverable.cpp:5]: Oh I see. I was thinking of merging API section in EpochSys into Recoverable.

File: src/persist/pnew.hpp (hunk 9 above)
Comment (qtcwt) [reply src/persist/pnew.hpp]: Nice.

File: src/rideables/MontageMSQueue.hpp (hunk 16 above)
Comment (qtcwt) [reply src/rideables/MontageMSQueue.hpp]: Yes I agree with this.

File: src/persist/EpochSys.hpp (hunk 6 above)
Comment (qtcwt) [reply src/persist/EpochSys.hpp:127]: Where do we currently persist this `x`?

File: src/persist/persist_utils.hpp [hunk 18]
```diff
@@ -2,9 +2,43 @@
...
+    UIDGenerator(){}
+    UIDGenerator(uint64_t task_num){
+        init(task_num);
+    }
+    ~UIDGenerator(){
+        if (curr_ids){
+            delete curr_ids;
+        }
+    }
+    void init(uint64_t task_num){
```
Comment (qtcwt) [inline src/persist/persist_utils.hpp:23]: Some comments here would be useful, otherwise in the future people would find it hard to understand what's going on here; I took several minutes to follow the logic. Some comments like "reserve the most significant `64-shift` bits for threads' id in UID, and the rest for generating UID in each thread" would be intuitive enough, I think.

File: src/persist/persist_utils.hpp [hunk 19]
```diff
@@ -2,9 +2,43 @@
...
+        }
+        if (!curr_ids){
+            curr_ids = new padded<uint64_t>[max];
+        }
+        for (uint64_t i = 0; i < max; i++){
+            curr_ids[i].ui = i << shift;
+        }
+    }
+    uint64_t get_id(int tid){
+        return curr_ids[tid].ui++;
```
Comment (qtcwt) [inline src/persist/persist_utils.hpp:39]: What if there are many threads and `shift` is small enough for thread `t`'s `curr_ids` to overflow (i.e., catch up with `t+1`'s `curr_ids`)? Maybe some assert or boundary check here?

**Comment by qtcwt** [comment]
> I wasn't able to resolve the include dependencies at first, but I think I can do something similar right now.

Nice. Thanks!

File: src/persist/persist_utils.hpp (hunk 18 above)
Comment (roghnin) [reply src/persist/persist_utils.hpp:23]: Sure; I'll do that.

File: src/persist/persist_utils.hpp (hunk 19 above)
Comment (roghnin) [reply src/persist/persist_utils.hpp:39]: I'll add an assertion here. Thanks!

File: src/persist/EpochSys.hpp (hunk 6 above)
Comment (roghnin) [reply src/persist/EpochSys.hpp:127]: It's not done yet.
In a future PR I'll persist a bunch of Montage metadata in the `Epoch` node, including this `x`, mappings of multiple `Recoverable`'s using the same `EpochSys` for `PBlk` identifications, and other stuff.

File: src/persist/EpochSys.hpp [hunk 20]
```diff
@@ -449,21 +336,26 @@ T* EpochSys::register_alloc_pblk(T* b, uint64_t c){
...
     if (blk->blktype == INIT){
         blk->blktype = ALLOC;
     }
-    // to_be_persisted[c%4].push(blk);
+    if (blk->id == 0){
+        blk->id = uid_generator.get_id(tid);
+    }
+
     to_be_persisted->register_persist(blk, c);
     PBlk* data = blk->get_data();
```
Comment (qtcwt) [inline src/persist/EpochSys.hpp:313]: `get_data()` is obsolete?

**Review by qtcwt — COMMENTED** [review]
I've done sanity check of `pending_allocs`-related stuffs. Everything looks great to me!

File: src/persist/EpochSys.hpp (hunk 20 above)
Comment (roghnin) [reply src/persist/EpochSys.hpp:313]: Yes. I don't mind leaving this in the codebase as a hint -- I do think this is needed in the future for resizable structures like general `PString` implementations.

File: src/persist/EpochSys.hpp (hunk 6 above)
Comment (qtcwt) [reply src/persist/EpochSys.hpp:127]: Cool. Thanks. Setting this conversation resolved.
